/**
 * Agent-key signing (ENG-20358): the wire format against the SDKs' known-answer
 * vectors, the client choosing it over HMAC, and agent writes sent one at a
 * time so their nonces arrive in order.
 */
import test from "node:test";
import assert from "node:assert/strict";

import { ExchangeClient } from "../src/client.js";
import { hasCredentials, loadConfig } from "../src/config.js";
import { agentAuthHeaders } from "../src/wallet.js";

// The vectors pinned by every SDK (nexus-exchange-ts `test/agent.test.ts`,
// nexus-exchange-rs `src/auth/agent.rs`), generated by the exchange frontend's
// signer and reproduced with `eth-account`. A drift in the canonical string,
// the prehash or the signature encoding fails here.
const VECTORS = [
  {
    key: "0x0101010101010101010101010101010101010101010101010101010101010101",
    method: "GET",
    path: "/account/summary",
    query: "",
    body: "",
    ts: 1_776_033_900_000,
    nonce: 1_776_033_900_000,
    agent: "0x1a642f0e3c3af545e7acbd38b07251b3990914f1",
    signature:
      "0xd94b40dff9c3d0e0a649178b6eb3159d9a3522a1ccc66390b42a7a444b8e52c8" +
      "5f2d2a9d66e8a48ac5040d8e96f526d352b3b7a686634280b9192eb6c12a61b61b",
  },
  {
    key: "0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318",
    method: "post",
    path: "/orders",
    query: "",
    body: '{"market_id":"BTC-USDX-PERP","side":"Buy","order_type":"Limit","quantity":"0.1","price":"50000"}',
    ts: 1_776_033_900_123,
    nonce: 42,
    agent: "0x2c7536e3605d9c16a7a3d7b1898e529396a65c23",
    signature:
      "0xeef09105834062da10d208be38311995d04cbc5e05043b89e7cbe6d4497d11b5" +
      "1f61729639551a8cfb6ea3e4fe0765afeba7bf3b5f5e09f63bc095c89005b61d1c",
  },
  {
    key: "0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318",
    method: "DELETE",
    path: "/orders",
    query: "market_id=BTC-USDX-PERP",
    body: "",
    ts: 1_776_033_900_456,
    nonce: 43,
    agent: "0x2c7536e3605d9c16a7a3d7b1898e529396a65c23",
    signature:
      "0x002554d4216daa303818dfcc5a15eb86940691e11ad6ab25a270916ec5a43a1a" +
      "5eb4c18dd898aa3ebd099c1683337e3c545417c2b67a0d384f1d0355ffa807f91c",
  },
];

const KEY = VECTORS[1].key;

test("agentAuthHeaders matches the SDKs' known-answer vectors", () => {
  for (const v of VECTORS) {
    assert.deepEqual(
      agentAuthHeaders(v.key, {
        method: v.method,
        path: v.path,
        query: v.query,
        body: new TextEncoder().encode(v.body),
        timestampMs: v.ts,
        nonce: v.nonce,
      }),
      {
        "x-agent": v.agent,
        "x-timestamp": String(v.ts),
        "x-nonce": String(v.nonce),
        "x-signature": v.signature,
      },
      `${v.method} ${v.path}`,
    );
  }
});

test("a bad agent key is refused without quoting it", () => {
  assert.throws(
    () =>
      agentAuthHeaders("0xdeadbeef", {
        method: "GET",
        path: "/x",
        query: "",
        body: new Uint8Array(),
        timestampMs: 1,
        nonce: 1,
      }),
    (err: Error) =>
      /NEXUS_EXCHANGE_AGENT_PRIVATE_KEY/.test(err.message) &&
      !err.message.includes("deadbeef"),
  );
});

test("NEXUS_EXCHANGE_AGENT_PRIVATE_KEY alone is a credential", () => {
  const cfg = loadConfig({ NEXUS_EXCHANGE_AGENT_PRIVATE_KEY: ` ${KEY}\n` });
  assert.equal(cfg.agentPrivateKey, KEY);
  assert.ok(hasCredentials(cfg));
});

type Call = { url: string; headers: Headers; body: Uint8Array };

function captureFetch(
  calls: Call[],
  respond: (url: string) => Promise<void> = async () => {},
) {
  const realFetch = globalThis.fetch;
  globalThis.fetch = (async (url: string, init: RequestInit) => {
    calls.push({
      url,
      headers: new Headers(init.headers),
      body: init.body
        ? new Uint8Array(init.body as Uint8Array)
        : new Uint8Array(),
    });
    await respond(url);
    return new Response("{}", { status: 200 });
  }) as typeof fetch;
  return () => {
    globalThis.fetch = realFetch;
  };
}

test("an agent key signs with agentAuth and wins over an HMAC pair", async () => {
  const client = new ExchangeClient({
    baseUrl: "http://example.test/v1",
    apiKey: "nx_test",
    apiSecret: "00".repeat(32),
    agentPrivateKey: KEY,
  });
  const calls: Call[] = [];
  const restore = captureFetch(calls);
  try {
    await client.request({
      method: "DELETE",
      path: "/orders",
      query: "market_id=BTC-USDX-PERP",
      body: { a: 1 },
      signed: true,
    });
  } finally {
    restore();
  }
  const h = calls[0].headers;
  assert.equal(h.get("x-api-key"), null, "HMAC must not ride along");
  // Re-sign what went out: the bare path (not the base's /v1), the query and
  // the exact body bytes are what the signature covers.
  assert.deepEqual(
    agentAuthHeaders(KEY, {
      method: "DELETE",
      path: "/orders",
      query: "market_id=BTC-USDX-PERP",
      body: calls[0].body,
      timestampMs: Number(h.get("x-timestamp")),
      nonce: Number(h.get("x-nonce")),
    }),
    {
      "x-agent": h.get("x-agent"),
      "x-timestamp": h.get("x-timestamp"),
      "x-nonce": h.get("x-nonce"),
      "x-signature": h.get("x-signature"),
    },
  );
  assert.equal(h.get("x-agent"), VECTORS[1].agent);
});

test("agent writes go one at a time with rising nonces; reads do not wait", async () => {
  const client = new ExchangeClient({
    baseUrl: "http://example.test",
    agentPrivateKey: KEY,
  });
  const calls: Call[] = [];
  let release!: () => void;
  const gate = new Promise<void>((r) => (release = r));
  let writes = 0;
  const restore = captureFetch(calls, async (url) => {
    if (url.endsWith("/orders") && ++writes === 1) await gate;
  });
  try {
    const first = client.request({
      method: "POST",
      path: "/orders",
      body: {},
      signed: true,
    });
    const second = client.request({
      method: "POST",
      path: "/orders",
      body: {},
      signed: true,
    });
    const read = client.request({ path: "/account/summary", signed: true });
    await read;
    // The first write is still in flight, so the second has not been sent.
    assert.deepEqual(calls.map((c) => new URL(c.url).pathname).sort(), [
      "/account/summary",
      "/orders",
    ]);
    release();
    await Promise.all([first, second]);
  } finally {
    restore();
  }
  const sent = calls.filter((c) => c.url.endsWith("/orders"));
  assert.equal(sent.length, 2);
  assert.ok(
    Number(sent[1].headers.get("x-nonce")) >
      Number(sent[0].headers.get("x-nonce")),
  );
});
